services:
  - type: web
    name: slaq-v001
    env: python
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
